apiVersion: v1
name: opensearchserverless-chart
description: A Helm chart for the ACK service controller for Amazon OpenSearch Serverless (opensearchserverless)
version: 0.2.3
appVersion: 0.2.3
home: https://github.com/aws-controllers-k8s/opensearchserverless-controller
icon: https://raw.githubusercontent.com/aws/eks-charts/master/docs/logo/aws.png
sources:
  - https://github.com/aws-controllers-k8s/opensearchserverless-controller
maintainers:
  - name: ACK Admins
    url: https://github.com/orgs/aws-controllers-k8s/teams/ack-admin
  - name: opensearchserverless Admins
    url: https://github.com/orgs/aws-controllers-k8s/teams/opensearchserverless-maintainer
keywords:
  - aws
  - kubernetes
  - opensearchserverless
